name: Tests

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

jobs:
  unit_tests:
    runs-on: bitex-self-hosted-runner
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Run unit and integration tests
        run: |
          docker build -t ${{ inputs.artifact_name }}-test --target tests .
